model:
  type: base_ae_no_maxpool_v2
  model_name: base_ae_no_maxpool_v2
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 64
  epochs: 3000
  learning_rate: 3.0e-03
  eval_epochs: 500
  output_dir: ./artifacts
  loss: "mse"
  run_name: base_ae_no_maxpool_v2_ext-b_2-lr_3e04
  b_t: 2